language: go
go:
  - "1.10"
before_install:
  - go get github.com/schrej/godacov
  - go get github.com/boltdb/bolt
  - go get github.com/go-yaml/yaml
  - go get github.com/golang/protobuf/proto
  - go get github.com/op/go-logging
  - go get golang.org/x/net/context
  - go get google.golang.org/grpc
script:
  - go test -coverprofile=coverage.out ./...
after_success:
  - godacov -t $CODACY_TOKEN -r ./coverage.out -c $TRAVIS_COMMIT
