# Election timeout average in milliseconds.
election_timeout: 225

# Election timeout jitter in milliseconds.
election_timeout_jitter: 75

# Port for the REST API to listen on for AppendEntries and RequestVote calls.
api_port: 8000
