// Code generated by protoc-gen-go.
// source: goraft.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	goraft.proto

It has these top-level messages:
	AppendEntriesRequest
	AppendEntriesResponse
	RequestVoteRequest
	RequestVoteResponse
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppendEntriesRequest struct {
	Term         uint32                        `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	LeaderId     string                        `protobuf:"bytes,2,opt,name=leaderId" json:"leaderId,omitempty"`
	PrevLogIndex uint32                        `protobuf:"varint,3,opt,name=prevLogIndex" json:"prevLogIndex,omitempty"`
	PrevLogTerm  uint32                        `protobuf:"varint,4,opt,name=prevLogTerm" json:"prevLogTerm,omitempty"`
	Entries      []*AppendEntriesRequest_Entry `protobuf:"bytes,5,rep,name=entries" json:"entries,omitempty"`
	LeaderCommit uint32                        `protobuf:"varint,6,opt,name=leaderCommit" json:"leaderCommit,omitempty"`
}

func (m *AppendEntriesRequest) Reset()                    { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()               {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AppendEntriesRequest) GetTerm() uint32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *AppendEntriesRequest) GetPrevLogIndex() uint32 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogTerm() uint32 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesRequest) GetEntries() []*AppendEntriesRequest_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntriesRequest) GetLeaderCommit() uint32 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type AppendEntriesRequest_Entry struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *AppendEntriesRequest_Entry) Reset()                    { *m = AppendEntriesRequest_Entry{} }
func (m *AppendEntriesRequest_Entry) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesRequest_Entry) ProtoMessage()               {}
func (*AppendEntriesRequest_Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *AppendEntriesRequest_Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AppendEntriesRequest_Entry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AppendEntriesResponse struct {
	Term    uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *AppendEntriesResponse) Reset()                    { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()               {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppendEntriesResponse) GetTerm() uint32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RequestVoteRequest struct {
	Term         uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	CandidateId  string `protobuf:"bytes,2,opt,name=candidateId" json:"candidateId,omitempty"`
	LastLogIndex uint32 `protobuf:"varint,3,opt,name=lastLogIndex" json:"lastLogIndex,omitempty"`
	LastLogTerm  uint32 `protobuf:"varint,4,opt,name=lastLogTerm" json:"lastLogTerm,omitempty"`
}

func (m *RequestVoteRequest) Reset()                    { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()               {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RequestVoteRequest) GetTerm() uint32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRequest) GetCandidateId() string {
	if m != nil {
		return m.CandidateId
	}
	return ""
}

func (m *RequestVoteRequest) GetLastLogIndex() uint32 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogTerm() uint32 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	Term        uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	VoteGranted bool   `protobuf:"varint,2,opt,name=voteGranted" json:"voteGranted,omitempty"`
}

func (m *RequestVoteResponse) Reset()                    { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()               {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RequestVoteResponse) GetTerm() uint32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteResponse) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

func init() {
	proto.RegisterType((*AppendEntriesRequest)(nil), "goraft.AppendEntriesRequest")
	proto.RegisterType((*AppendEntriesRequest_Entry)(nil), "goraft.AppendEntriesRequest.Entry")
	proto.RegisterType((*AppendEntriesResponse)(nil), "goraft.AppendEntriesResponse")
	proto.RegisterType((*RequestVoteRequest)(nil), "goraft.RequestVoteRequest")
	proto.RegisterType((*RequestVoteResponse)(nil), "goraft.RequestVoteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GoRaft service

type GoRaftClient interface {
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
}

type goRaftClient struct {
	cc *grpc.ClientConn
}

func NewGoRaftClient(cc *grpc.ClientConn) GoRaftClient {
	return &goRaftClient{cc}
}

func (c *goRaftClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := grpc.Invoke(ctx, "/goraft.GoRaft/AppendEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goRaftClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	out := new(RequestVoteResponse)
	err := grpc.Invoke(ctx, "/goraft.GoRaft/RequestVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoRaft service

type GoRaftServer interface {
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
}

func RegisterGoRaftServer(s *grpc.Server, srv GoRaftServer) {
	s.RegisterService(&_GoRaft_serviceDesc, srv)
}

func _GoRaft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoRaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goraft.GoRaft/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoRaftServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoRaft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoRaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goraft.GoRaft/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoRaftServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoRaft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goraft.GoRaft",
	HandlerType: (*GoRaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _GoRaft_AppendEntries_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _GoRaft_RequestVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goraft.proto",
}

func init() { proto.RegisterFile("goraft.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x93, 0x41, 0x4f, 0xea, 0x40,
	0x10, 0xc7, 0x5f, 0x29, 0x2d, 0x30, 0x40, 0xf2, 0x32, 0x8f, 0x97, 0x34, 0x7d, 0xcf, 0x84, 0xf4,
	0xc4, 0x09, 0x13, 0xbc, 0x7a, 0x51, 0x43, 0x90, 0x68, 0x3c, 0x34, 0xc6, 0x83, 0xb7, 0xda, 0x1d,
	0x09, 0x11, 0xba, 0x75, 0x77, 0x21, 0xf2, 0x2d, 0xfc, 0x06, 0x26, 0x7e, 0x52, 0xdb, 0x6d, 0x4b,
	0x16, 0x44, 0x6e, 0xfb, 0xff, 0xef, 0xcc, 0xf4, 0x37, 0xff, 0x4d, 0xa1, 0x33, 0xe3, 0x22, 0x7a,
	0x56, 0xc3, 0x54, 0x70, 0xc5, 0xd1, 0x2d, 0x54, 0xf0, 0x51, 0x83, 0xde, 0x45, 0x9a, 0x52, 0xc2,
	0xc6, 0x89, 0x12, 0x73, 0x92, 0x21, 0xbd, 0xae, 0x48, 0x2a, 0x44, 0xa8, 0x2b, 0x12, 0x4b, 0xcf,
	0xea, 0x5b, 0x83, 0x6e, 0xa8, 0xcf, 0xe8, 0x43, 0x73, 0x41, 0x11, 0x23, 0x31, 0x65, 0x5e, 0x2d,
	0xf3, 0x5b, 0xe1, 0x56, 0x63, 0x00, 0x9d, 0x54, 0xd0, 0xfa, 0x96, 0xcf, 0xa6, 0x09, 0xa3, 0x37,
	0xcf, 0xd6, 0x7d, 0x3b, 0x1e, 0xf6, 0xa1, 0x5d, 0xea, 0xfb, 0x7c, 0x74, 0x5d, 0x97, 0x98, 0x16,
	0x9e, 0x43, 0x83, 0x0a, 0x0e, 0xcf, 0xe9, 0xdb, 0x83, 0xf6, 0x28, 0x18, 0x96, 0xd8, 0x87, 0x20,
	0x87, 0xb9, 0xdc, 0x84, 0x55, 0x4b, 0xce, 0x50, 0xf0, 0x5c, 0xf1, 0xe5, 0x72, 0xae, 0x3c, 0xb7,
	0x60, 0x30, 0x3d, 0xff, 0x14, 0x1c, 0xdd, 0x85, 0xbf, 0xc1, 0x7e, 0xa1, 0x8d, 0xde, 0xaf, 0x15,
	0xe6, 0x47, 0xec, 0x81, 0xb3, 0x8e, 0x16, 0x2b, 0x2a, 0x77, 0x2b, 0x44, 0x30, 0x86, 0xbf, 0x7b,
	0xdf, 0x96, 0x29, 0x4f, 0x24, 0x1d, 0x4c, 0xc8, 0x83, 0x86, 0x5c, 0xc5, 0x31, 0x49, 0xa9, 0x87,
	0x34, 0xc3, 0x4a, 0x06, 0xef, 0x16, 0x60, 0x89, 0xfd, 0xc0, 0x15, 0x1d, 0x8b, 0x39, 0x8b, 0x29,
	0x8e, 0x12, 0x36, 0x67, 0x91, 0xa2, 0x6d, 0xd2, 0xa6, 0xa5, 0x17, 0x8d, 0xa4, 0xda, 0x0f, 0xdb,
	0xf4, 0xf2, 0x29, 0xa5, 0x36, 0xc3, 0x36, 0xac, 0xe0, 0x06, 0xfe, 0xec, 0x10, 0x1d, 0xd9, 0x2b,
	0x1b, 0xb6, 0xce, 0x6a, 0x26, 0x22, 0x4a, 0x14, 0xb1, 0x72, 0x37, 0xd3, 0x1a, 0x7d, 0x5a, 0xe0,
	0x4e, 0x78, 0x98, 0x3d, 0x15, 0xde, 0x41, 0x77, 0x27, 0x31, 0xfc, 0x7f, 0xec, 0x11, 0xfd, 0x93,
	0x1f, 0x6e, 0x0b, 0x9c, 0xe0, 0x17, 0x5e, 0x43, 0xdb, 0xe0, 0x44, 0xbf, 0xaa, 0xff, 0x1e, 0xa7,
	0xff, 0xef, 0xe0, 0x5d, 0x35, 0xe9, 0xd2, 0x79, 0xb4, 0x45, 0x1a, 0x3f, 0xb9, 0xfa, 0x1f, 0x38,
	0xfb, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xe4, 0xf6, 0xcf, 0x13, 0x03, 0x00, 0x00,
}
